services:
  # Nombre del servicio: db-datos (todo minúsculas)
  db-datos:
    image: mysql:8.0
    container_name: db_innovatech
    environment:
      - MYSQL_DATABASE=innovatech_db
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=user_devops
      - MYSQL_PASSWORD=pass_devops
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - red_interna

  # Nombre del servicio: back-ventas (todo minúsculas)
  back-ventas:
    build:
      context: "./back-Ventas_SpringBoot/Springboot-API-REST"
      dockerfile: Dockerfile # Le decimos explícitamente cómo se llama
    container_name: micro-ventas

    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-datos:3306/innovatech_db
      - SPRING_DATASOURCE_USERNAME=user_devops
      - SPRING_DATASOURCE_PASSWORD=pass_devops
    depends_on:
      - db-datos
    networks:
      - red_interna

  # Nombre del servicio: back-despachos (todo minúsculas - AQUÍ ESTABA EL ERROR)
  back-despachos:
    build:
      context: "./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO"
      dockerfile: Dockerfile # Le decimos explícitamente cómo se llama
    container_name: micro-despachos
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-datos:3306/innovatech_db
      - SPRING_DATASOURCE_USERNAME=user_devops
      - SPRING_DATASOURCE_PASSWORD=pass_devops
    depends_on:
      - db-datos
    networks:
      - red_interna

  # Nombre del servicio: frontend (todo minúsculas)
  frontend:
    build:
      context: "./front_despacho"
      dockerfile: Dockerfile # Le decimos explícitamente cómo se llama
    container_name: front_innovatech
    ports:
      - "80:80"
    networks:
      - red_interna

networks:
  red_interna:
    driver: bridge

volumes:
  mysql_data: